// This file is auto-generated by Payload CMS.
// Do not edit this file directly.

export interface User {
  id: string;
  email: string;
  role: 'admin' | 'owner';
  tenants?: Array<{ tenant: string | Workspace }>;
  createdAt: string;
  updatedAt: string;
}

export interface Workspace {
  id: string;
  name: string;
  slug: string;
  status: 'active' | 'paused' | 'disabled';
  createdAt: string;
  updatedAt: string;
}